ДЗ1. Вёрстка макета.
Kirillishko/homeworks pull request #1
Opened 2023-12-31 13:58 UTC by Kirillishko

2024-01-09 12:50 UTC, st-slav commented
Давай папки:
.history
.idea
добавим в .gitignore

2024-01-09 13:02 UTC, Kirillishko commented
Спасибо, добавил.

2024-01-09 13:36 UTC, st-slav requested changes

2024-01-09 13:36 UTC, st-slav commented on src/product.html
> +                <h4>Nulla et mauris sed elit semper pretium a quis augue. Fusce tempus est ex, eu porttitor nulla auctor
думаю что ```<p>``` здесь более подходящий тег

2024-01-09 13:36 UTC, st-slav commented on src/product.html
> +                <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ultrices ante sit amet mollis luctus.
думаю что ```<p>``` здесь более подходящий тег

2024-01-09 13:36 UTC, st-slav commented on src/product.css
> +    fill: #e97f03;
думаю что этот цвет можно вынести в переменную

2024-01-09 13:36 UTC, st-slav commented on src/index.html
> +            <h3>$129</h3>
не совсем уверен что h3 здесь подходящий тег

2024-01-09 13:36 UTC, st-slav commented on src/index.html
> +            <a href="product.html"><h2>G Home</h2></a>
для скрин ридеров лучше a разместить в h2

2024-01-09 18:02 UTC, chagins commented on src/header.css
> +    margin-bottom: 0;
Можно записать одним свойством: top, left & right, bottom

2024-01-09 19:05 UTC, chagins commented
@Kirillishko, вложи пж в pr скрины получившейся верстки, со списком товаров и с одним товаром.

2024-01-09 19:07 UTC, chagins requested changes

2024-01-09 19:07 UTC, chagins commented on src/product.html
> +<body>
вложенные в body элементы по идее должны иметь отступ. Это мелочь, но читаемость лучше, можно использовать prettier, для быстрого форматирования (в webstorm должен быть встроен).

2024-01-09 19:07 UTC, chagins commented on src/product.html
> +</body>
вложенные в body элементы по идее должны иметь отступ. Это мелочь, но читаемость лучше, можно использовать prettier, для быстрого форматирования (в webstorm должен быть встроен).

2024-01-11 09:47 UTC, chagins approved these changes

2024-01-11 09:51 UTC, st-slav approved these changes

2024-01-11 09:51 UTC, merged