ДЗ 2. Получение данных на странице и поиск.
Kirillishko/homeworks pull request #2
Opened 2024-01-12 15:57 UTC by Kirillishko

### Задание:
_1. реализовать получение данных на странице списка
2. реализовать получение данных на странице карточки
3. логику по получению данных вынести в отдельный файл, назвать его например api.js, вообще не лепите всё в один файл, старайтесь разносить всё по модулям
4. реализовать поиск на странице списка по свойству name у полученных записей_

Результат: 
![image](https://github.com/Kirillishko/homeworks/assets/97043155/eac57f64-d869-4af4-8f40-9308ba1599c2)
![image](https://github.com/Kirillishko/homeworks/assets/97043155/8ca66fe0-1c42-48e2-ab01-e8c68f496abf)
![image](https://github.com/Kirillishko/homeworks/assets/97043155/13044187-0901-437b-ba77-cdee1a62a38b)
![image](https://github.com/Kirillishko/homeworks/assets/97043155/c3cf7abd-ffce-4d14-bfd4-43eafc741dd9)
![image](https://github.com/Kirillishko/homeworks/assets/97043155/e5d01f0d-2483-4589-995b-ddca866aaa6b)

К каждой ссылке в конец добавляется id товара, на странице товара он ищёт по этому id.
Также при поиске на товарах остаётся лайк.

2024-01-14 07:04 UTC, chagins commented on src/js/MainPageRenderer.js
> +		throw new Error(e);
`throw`` в блоке `catch` вызывет необработанное исключение.
`throw` обычно используется в блоке try для того, чтобы вызвать ошибку, которая "провалится" в catch.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw

2024-01-14 07:16 UTC, chagins commented on src/js/MainPageRenderer.js
> +		const products = data.content;
Можно использовать деструктуризацию объекта при получении продуктов, записать в одну строку

2024-01-14 07:40 UTC, chagins commented on src/js/MainPageRenderer.js
> +		const image = getPicture(picture.path);
По неймингу:
`finalPrice` не совсем понятное название, можно использовать, например `priceWithSign`
`getPicture` и 'image' - могут расцениваться по разному, в данном случае подойдет `imagePath = getImagePath`

2024-01-14 07:44 UTC, chagins commented on src/js/MainPageRenderer.js
> +	for (const product of products) {
Попробуй использовать встроенные методы массивов.
Будет норм если используешь forEach, а еще круче если сможешь реализовать с помощью reduce
`const html = products.reduce(...`

2024-01-14 08:07 UTC, chagins commented on src/js/MainPageRenderer.js
> +		}
Имя класса `none` не совсем понятное, можно использовать например `hidden` 
`else if (!card.classList.contains('none')` избыточно, можно написать `else` и добавить нужный класс.

2024-01-14 08:37 UTC, chagins commented on src/styles/reset.css
> +}
`reset.css` для сброса стилей.
`!important` используется в крайнем случае, например при использовании сторонней ui библиотеки и невозможности переопределить стили по другому, тут можно обойтись без использования этого свойства.
`none` не совсем понятное название, используй, например `hidden`.

2024-01-14 08:48 UTC, chagins commented on src/js/MainPageRenderer.js
> +		const cardName = card.querySelector('.info').getElementsByTagName('a')[0].textContent.toLowerCase();
Предлагаю для элемента, который содержит название, добавить класс, чтобы уменьшить цепочку поиска
`card.querySelector('.card-name')`

2024-01-14 09:02 UTC, chagins commented on src/js/ProductPageRenderer.js
> +	let value = Math.floor(+e.target.value);
по умолчанию нужно использовать `const`

2024-01-14 09:05 UTC, chagins commented on src/js/ProductPageRenderer.js
> +	else e.target.value = value;
рекомендуется всегда использовать фигурные скобки,
но здесь выражение можно записать тернарным оператором

2024-01-14 09:15 UTC, chagins commented on src/js/MainPageRenderer.js
> +const main = document.getElementById('root-container');
Лучше использовать более точные имена, например mainContainer, или rootContainer

2024-01-14 09:15 UTC, chagins commented on src/js/ProductPageRenderer.js
> +const main = document.getElementById('root-container');
Лучше использовать более точные имена, например mainContainer, или rootContainer

2024-01-14 15:54 UTC, chagins commented on src/js/helpers.js
> +export default convertCurrencyToSign;
файл helpers предназначен для набора вспомогательных функций, поэтому тут не нужен импорт по умолчанию. Ожидается что будут другие ф-ии.

2024-01-14 16:30 UTC, chagins approved these changes

2024-01-15 06:37 UTC, st-slav requested changes

2024-01-15 06:37 UTC, st-slav commented on src/js/ProductPageRenderer.js
> +	e.preventDefault();
e.preventDefault() точно нужен?

2024-01-15 06:37 UTC, st-slav commented on src/js/MainPageRenderer.js
> +		const image = getPicture(picture.path);
или showPrice

2024-01-15 06:37 UTC, st-slav commented on src/js/ProductPageRenderer.js
> +		const href = window.location.href;
для работы с path можно использовать URLSearchParams
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
https://learn.javascript.ru/url

2024-01-15 06:37 UTC, st-slav commented on src/pages/index.html
> +		<link href="../styles/globals.css" rel="stylesheet" />
здесь и в подобных, лучше использовать относительный пут, по идее он здесь должен работать
https://sergeybr94.medium.com/%D0%BE%D1%82%D0%BD%D0%BE%D1%81%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BF%D1%83%D1%82%D1%8C-%D0%BA-%D1%84%D0%B0%D0%B9%D0%BB%D1%83-2874d19ca0a1

2024-01-15 07:15 UTC, st-slav approved these changes

2024-01-15 07:15 UTC, merged