ДЗ 5. React и TypeScript
Kirillishko/homeworks pull request #5
Opened 2024-01-21 16:13 UTC by Kirillishko

### Задание

_1. Переписать приложение с использованием react (использовать хуки и функциональные компоненты)
2. Добавить TypeScript в приложение_

2024-01-22 14:53 UTC, Kirillishko commented on webpack.config.js
> +    // },
Готово.

2024-01-22 14:54 UTC, Kirillishko commented on src/App.tsx
> +    const filterProducts = () => {
Готово.

2024-01-22 14:54 UTC, Kirillishko commented on src/hooks/useDebounce.ts
> +}
Готово.

2024-01-22 14:55 UTC, Kirillishko commented on src/App.tsx
> +        const value = e.target.value.toLowerCase();
Готово.

2024-01-22 14:55 UTC, Kirillishko commented on src/components/ProductList/ProductList.tsx
> +        <div className={styles.container} >
Добавил компонент Loader

2024-01-22 14:55 UTC, Kirillishko commented on src/components/ProductItem/ProductItem.tsx
> +            <Link to={`products/${id}`} ><img alt={picture.alt} src={imagePath} /></Link >
Готово.

2024-01-22 14:55 UTC, Kirillishko commented on src/components/ProductPage/ProductPage.tsx
> +    }, []);
Готово.

2024-01-22 14:55 UTC, Kirillishko commented on src/types/IProduct.ts
> +
Убрал.

2024-01-22 17:05 UTC, MariyaKustova commented on src/components/ProductPage/ProductPage.tsx
> +    }, []);
Если настроишь линтер, то увидишь, что здесь обязательно должен быть в массиве зависимостей id.
Повторюсь, здесь должна быть проверка на наличие id
    
useEffect(() => {
  if(id) {
        getItem(id.toString()).then(product => setProduct(product));
}
    }, [id]);

2024-01-22 17:05 UTC, MariyaKustova commented on src/helpers.ts
> +    const filter = inputSearch.toLowerCase();
Подскажи пжл, зачем ты это делаешь? Это повторение того, что ты уже сделал, когда в Header записал значение input в setSearchInput

2024-01-22 17:05 UTC, MariyaKustova commented on src/components/Header/Header.tsx
> +        const value = e.target.value.toLowerCase();
Как вариант, еще можно удалить пробелы в строке значения - .trim()
Этот момент частенько вызывает баги

2024-01-22 17:05 UTC, MariyaKustova commented on src/types/IProduct.ts
> +    details?: string,
Обычно опциональные поля описываются в самом конце.

2024-01-22 17:14 UTC, MariyaKustova commented on src/components/ProductPage/ProductPage.tsx
> +    const [isLoading, product] = useApi(() => getItem(id!.toString()), null);
Ты хотел сделать универсальный хук - это круто, но в качестве аргумента, например, можно передавать объект с полями, которые могут послужить флагами. Смотри, здесь id может быть undefined. Но ты делаешь запрос - это неправильно. Всегда должна быть проверка, код должен быть защищен.
Мы на проекте недавно договорились с ребятами, что если функция или хук принимает больше 2 аргументов, то они должны быть упакованы в объект.

2024-01-22 17:16 UTC, MariyaKustova commented on src/hooks/useDebouncedCallback.ts
> +export default useDebouncedCallback;
Я не нашла его использования в коде. Если на него никто не ссылается - его нужно удалить

2024-01-22 17:16 UTC, MariyaKustova commented on src/components/Modal/Modal.tsx
> +export default Modal;
Подскажи пжл, в каком случае появляется это модальное окно? Не смогла найти ссылку...

2024-01-23 07:52 UTC, st-slav requested changes

2024-01-23 07:52 UTC, st-slav commented on package.json
> +    "@types/node": "^20.11.5",
библиотеки с типами можно унести в  "devDependencies"

2024-01-23 07:52 UTC, st-slav commented on package.json
> +    "react-scripts": "5.0.1",
по идее react-scripts тоже можно унести  в "devDependencies"

2024-01-23 07:52 UTC, st-slav commented on package.json
> +    "typescript": "^4.9.5"
по идее typescript тоже можно унести в "devDependencies", но тут не уверен, надо попробовать!

2024-01-23 07:52 UTC, st-slav commented on src/api/HttpClient.ts
> +HttpClient.interceptors.request.use(
похоже что это сейчас не нужно

2024-01-23 07:52 UTC, st-slav commented on src/api/HttpClient.ts
> +HttpClient.interceptors.response.use(
похоже что это сейчас не нужно

2024-01-23 07:52 UTC, st-slav commented on src/api/HttpClient.ts
> +export {HttpClient, apiPass};
давай export писать сразу перед функцией которую экспортируешь

2024-01-23 07:52 UTC, st-slav commented on src/api/api.ts
> +const getItem = (itemId: string | number): Promise<IProduct> => getData(`/item/${itemId}`);
по моему itemId может быть только строкой

2024-01-23 07:52 UTC, st-slav commented on src/api/api.ts
> +export {getItems, getItem, getImagePath};
экспорт перед функциями

2024-01-23 07:52 UTC, st-slav commented on src/components/Loader/Loader.tsx
> +            <span className={styles.loader} ></span >
```<span className={styles.loader} />```

2024-01-23 07:52 UTC, st-slav commented on src/components/Modal/Modal.tsx
> +    children?: any
children?: ReactNode

2024-01-23 07:52 UTC, st-slav commented on src/components/Modal/Modal.tsx
> +                <input type="button" value="Закрыть" onClick={() => setActive(prevState => !prevState)} />
эту логику ( setActive(prevState => !prevState) ) лучше оставить наверху, а сюда передавать функцию onClose например

2024-01-23 07:52 UTC, st-slav commented on src/components/Product/Product.tsx
> +                            <svg className={styles.favoriteIcon} >
давай svg вынесем в отдельный компонент, либо вообще в отдельный svg файл

https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

2024-01-23 07:52 UTC, st-slav commented on src/App.tsx
> +    const [, products] = useApi(getItems, []);
не получится это унести в компонент роута в котором будет использоваться?

2024-01-23 07:52 UTC, st-slav commented on src/components/Header/Header.tsx
> +                    <svg height="24px" viewBox="0 0 24 24" width="24px" >
svg в assets

https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

2024-01-23 07:52 UTC, st-slav commented on src/components/ProductItem/ProductItem.tsx
> +                <svg className={styles.favoriteIcon} >
svg в assets

2024-01-23 07:52 UTC, st-slav commented on webpack.config.js
> -const path = require('path');
этот конфиг нужен сейчас? по идее сейчас используется сборка CRA

2024-01-23 08:00 UTC, st-slav requested changes

2024-01-23 08:00 UTC, st-slav commented on src/components/Modal/Modal.tsx
> +const Modal = ({active, setActive, children}: ModalProps) => {
можно писать так:
const Modal: React.FC<ModalProps> = ({active, setActive, children}) => {

2024-01-23 08:40 UTC, st-slav requested changes

2024-01-23 08:40 UTC, st-slav commented on src/App.tsx
> +import ProductPage from "./components/ProductPage/ProductPage";
страницы полностью лучше хранить в папке pages

2024-01-23 08:40 UTC, st-slav commented on src/App.tsx
> +import ProductList from "./components/ProductList/ProductList";
страницы полностью лучше хранить в папке pages

2024-01-23 17:08 UTC, Kirillishko commented on src/hooks/useApi.ts
> +const useApi = <T>(fetch: () => Promise<T>, initialState: T): [boolean, T] => {
Переименовал на useDataLoader.

2024-01-23 17:08 UTC, Kirillishko commented on src/App.tsx
> +    const searchDelay = 1000;
Вынес.

2024-01-23 17:08 UTC, Kirillishko commented on src/App.tsx
> +    const [, products] = useApi(getItems, []);
Сделал.

2024-01-23 17:10 UTC, Kirillishko commented on src/hooks/useDebouncedValue.ts
> +    }, [initialValue]);
В зависимости всё добавил и настроил линтер, с ним проще)

2024-01-23 17:10 UTC, Kirillishko commented on src/App.tsx
> +    const filteredProducts = useDebouncedValue(products, getFilteredProducts(products, searchInput), searchDelay);
Исправил.

2024-01-23 17:10 UTC, Kirillishko commented on src/components/Product/Product.tsx
> +    const minCounterValue = 1;
Вынес.

2024-01-23 17:11 UTC, Kirillishko commented on src/components/Product/Product.tsx
> +    const [productCount, setProductCount] = useState(1);
Исправил. А 0 не может быть потому что было бы странно, если бы в корзину можно было бы положить 0 товаров. Поэтому минимум 1.

2024-01-23 17:12 UTC, Kirillishko commented on src/components/ProductList/ProductList.tsx
> +        )
Исправил.

2024-01-23 17:12 UTC, Kirillishko commented on src/components/ProductPage/ProductPage.tsx
> +    }, []);
Исправил.

2024-01-23 17:12 UTC, Kirillishko commented on src/helpers.ts
> +    const filter = inputSearch.toLowerCase();
Случайно, убрал.

2024-01-23 17:12 UTC, Kirillishko commented on src/components/Header/Header.tsx
> +        const value = e.target.value.toLowerCase();
Сделал, спасибо.

2024-01-23 17:12 UTC, Kirillishko commented on src/types/IProduct.ts
> +    details?: string,
Переместил вниз.

2024-01-23 17:15 UTC, Kirillishko commented on src/hooks/useDebouncedCallback.ts
> +export default useDebouncedCallback;
Добавил, не мог места найти.

2024-01-23 17:16 UTC, Kirillishko commented on src/components/Modal/Modal.tsx
> +export default Modal;
До этого нигде не появлялось, не мог места найти. Уже сделал.

2024-01-23 17:16 UTC, Kirillishko commented on package.json
> +    "@types/node": "^20.11.5",
Перенёс.

2024-01-23 17:16 UTC, Kirillishko commented on package.json
> +    "react-scripts": "5.0.1",
Перенёс.

2024-01-23 17:22 UTC, Kirillishko commented on package.json
> +    "typescript": "^4.9.5"
Перенёс, в devDependencies можно уносить, на официальной странице TypeScript'а нашёл инфу.

2024-01-23 17:22 UTC, Kirillishko commented on src/api/HttpClient.ts
> +HttpClient.interceptors.request.use(
Убрал.

2024-01-23 17:23 UTC, Kirillishko commented on src/api/HttpClient.ts
> +export {HttpClient, apiPass};
Исправил.

2024-01-23 17:23 UTC, Kirillishko commented on src/api/api.ts
> +const getItem = (itemId: string | number): Promise<IProduct> => getData(`/item/${itemId}`);
Исправил.

2024-01-23 17:23 UTC, Kirillishko commented on src/api/api.ts
> +export {getItems, getItem, getImagePath};
Исправил.

2024-01-23 17:23 UTC, Kirillishko commented on src/components/Loader/Loader.tsx
> +            <span className={styles.loader} ></span >
Исправил.

2024-01-23 17:23 UTC, Kirillishko commented on src/components/Modal/Modal.tsx
> +    children?: any
Исправил.

2024-01-23 17:24 UTC, Kirillishko commented on src/components/Modal/Modal.tsx
> +                <input type="button" value="Закрыть" onClick={() => setActive(prevState => !prevState)} />
Сделал.

2024-01-23 17:24 UTC, Kirillishko commented on src/components/Product/Product.tsx
> +                            <svg className={styles.favoriteIcon} >
Вынес в компонент.

2024-01-23 17:25 UTC, Kirillishko commented on src/App.tsx
> +    const [, products] = useApi(getItems, []);
Я сделал отдельно компонент для страницы с продуктами.

2024-01-23 17:25 UTC, Kirillishko commented on src/components/Header/Header.tsx
> +                    <svg height="24px" viewBox="0 0 24 24" width="24px" >
Сделал.

2024-01-23 17:27 UTC, Kirillishko commented on webpack.config.js
> -const path = require('path');
Убрал.

2024-01-23 17:27 UTC, Kirillishko commented on src/components/Modal/Modal.tsx
> +const Modal = ({active, setActive, children}: ModalProps) => {
Все компоненты изменил.

2024-01-23 17:27 UTC, Kirillishko commented on src/App.tsx
> +import ProductPage from "./components/ProductPage/ProductPage";
Сделал.

2024-01-24 15:48 UTC, st-slav requested changes

2024-01-24 17:19 UTC, Kirillishko commented on src/App.tsx
> +    console.log("APP");
Убрал.

2024-01-24 17:19 UTC, Kirillishko commented on src/components/Header/Header.tsx
> +        console.log("onSearchInputChange");
Убрал.

2024-01-24 17:19 UTC, Kirillishko commented on src/components/Product/Product.tsx
> +                            {/*<svg className={styles.favoriteIcon} >*/}
Убрал.

2024-01-24 17:19 UTC, Kirillishko commented on src/hooks/useDataLoader.ts
> +            });
Переместил.

2024-01-24 17:19 UTC, Kirillishko commented on src/hooks/useDebouncedValue.ts
> +    console.log("useDebouncedValue start1");
Убрал.

2024-01-24 17:19 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +    console.log("ProductListPage");
Убрал.

2024-01-24 17:19 UTC, Kirillishko commented on src/hooks/useDataLoader.ts
> +                setError(error);
Сделал.

2024-01-24 17:20 UTC, Kirillishko commented on src/pages/ProductPage/ProductPage.tsx
> +            <ErrorModal title={"Ошибка"} description={"Нет данных!"} />
Исправил.

2024-01-24 17:20 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +            <ErrorModal title={"Ошибка"} description={"Нет данных!"} />
Исправил.

2024-01-24 17:20 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +        data.length > 0 ? (<ProductList products={filteredProducts} />
Исправил.

2024-01-24 17:20 UTC, Kirillishko commented on src/components/ProductPage/ProductPage.tsx
> +    const [isLoading, product] = useApi(() => getItem(id!.toString()), null);
Исправил.

2024-01-24 18:47 UTC, MariyaKustova commented on src/components/Header/Header.tsx
> +
Либо в одну строку, либо нужно обернуть в фигурные скобки

2024-01-24 18:47 UTC, MariyaKustova commented on src/hooks/useDebouncedValue.ts
>  export const useDebouncedValue = <T extends Primitives>(value: T, delay: number): T => {
Ох уж эта любовь к дженерикам) Значение здесь строка... Другого не дано)

2024-01-24 18:47 UTC, MariyaKustova commented on src/pages/ProductListPage/ProductListPage.tsx
> +            <Header setSearchInput={setSearchInput} />
Так как Header должен быть и в том и в другом случае, то лучше сделать так 
`return (
<>
![image](https://github.com/Kirillishko/homeworks/assets/58948550/cb66ad9c-e86f-4123-9f6b-2197fbc5690a)
</>
)

2024-01-24 18:47 UTC, MariyaKustova commented on src/pages/ProductListPage/ProductListPage.tsx
> +    const filter = useDebouncedValue(searchInput, SEARCH_DELAY);
Это не фильтр, а debouncedValue

2024-01-24 18:47 UTC, MariyaKustova commented on src/pages/ProductListPage/ProductListPage.tsx
> +    const [filteredProducts, setFilteredProducts] = useState<IProduct[]>();
Здесь не требуется useState и useEffect.
Можно сразу вычислять переменную 
const filteredProducts = getFilteredProducts(data, filter);

2024-01-24 18:47 UTC, MariyaKustova commented on src/pages/ProductPage/ProductPage.tsx
> +    const {isLoading, error, data} = useDataLoader(id);
id может быть undefined, а нам нужно передавать null, так как именно на эту ситуацию ты завязываешься в хуке

2024-01-24 18:47 UTC, MariyaKustova commented on src/pages/ProductPage/ProductPage.tsx
> +        </>
Перепиши, как показывала выше.

2024-01-24 18:47 UTC, MariyaKustova commented on src/hooks/useDataLoader.ts
> +const useDataLoader = (id?: string | null): {
Достаточно useData

2024-01-25 07:29 UTC, st-slav requested changes

2024-01-25 07:29 UTC, st-slav commented on src/components/Modal/Modal.tsx
> +                modalRootElement.removeChild(element);
удобнее читать код с if с фигурными скобками, а вообще можно так:
```modalRootElement?.removeChild(element);```

2024-01-25 07:29 UTC, st-slav commented on src/components/Modal/Modal.tsx
> +            modalRootElement.appendChild(element);
удобнее читать код с if с фигурными скобками, а вообще можно так:
```modalRootElement?.appendChild(element);```

2024-01-25 07:29 UTC, st-slav commented on src/components/Modal/Modal.tsx
> +    }, [element]);
можно создание элемента (document.createElement("div");) сделать сразу в useEffect, тем самым мы избавимся от useMemo

2024-01-25 07:29 UTC, st-slav commented on src/hooks/useDataLoader.ts
> +        if (id !== null) {
можно и создание самой функции loadData поместить в этот блок if, тем самым если id === null тогда и функция создаваться не будет, т. к. она всё равно не будет выполняться

2024-01-25 07:29 UTC, st-slav commented on src/hooks/useDataLoader.ts
> +            const fetch = id ? () => getItem(id) : getItems;
давай может переделаем этот хук и будем передавать сюда не id, а саму функцию для получения данных, тем самым если у нас появятся ещё методы для получения каких-нибудь сущностей, то мы сможем использовать этот хук и для них, т. е. функция fetch будет приходить из вне, связь будет ослаблена

2024-01-25 07:29 UTC, st-slav commented on src/pages/ProductListPage/ProductListPage.tsx
> +            setFilteredProducts(getFilteredProducts(data, filter));
для вычисления отфильтрованных, можно использовать useMemo, вместо useState + useEffect

2024-01-25 09:20 UTC, Kirillishko commented on src/components/Header/Header.tsx
> +
Сделал.

2024-01-25 09:20 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +            <Header setSearchInput={setSearchInput} />
Сделал.

2024-01-25 09:21 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +    const filter = useDebouncedValue(searchInput, SEARCH_DELAY);
Сделал.

2024-01-25 09:27 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +            setFilteredProducts(getFilteredProducts(data, filter));
Сделал.

2024-01-25 09:29 UTC, Kirillishko commented on src/hooks/useDataLoader.ts
> +            const fetch = id ? () => getItem(id) : getItems;
Я так и сделал изначально, но были проблемы с обработкой id на undefined, поэтому предлагаю лучше оставить так.

2024-01-25 09:29 UTC, Kirillishko commented on src/hooks/useDataLoader.ts
> +        if (id !== null) {
Сделал.

2024-01-25 09:30 UTC, Kirillishko commented on src/components/Modal/Modal.tsx
> +    }, [element]);
Element используется ещё в createPortal, поэтому предлагаю оставить так.

2024-01-25 09:30 UTC, Kirillishko commented on src/components/Modal/Modal.tsx
> +            modalRootElement.appendChild(element);
Сделал.

2024-01-25 09:30 UTC, Kirillishko commented on src/components/Modal/Modal.tsx
> +                modalRootElement.removeChild(element);
Сделал через ?.

2024-01-25 09:30 UTC, Kirillishko commented on src/hooks/useDataLoader.ts
> +const useDataLoader = (id?: string | null): {
Изменил.

2024-01-25 09:30 UTC, Kirillishko commented on src/pages/ProductPage/ProductPage.tsx
> +        </>
Сделал.

2024-01-25 09:30 UTC, Kirillishko commented on src/pages/ProductPage/ProductPage.tsx
> +    const {isLoading, error, data} = useDataLoader(id);
Изменил.

2024-01-25 09:32 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +    const [filteredProducts, setFilteredProducts] = useState<IProduct[]>();
Так напрямую не получалось, потому что data ещё не привидена к нужному типу. Я сделал как Стас предложил ниже,

2024-01-25 09:33 UTC, Kirillishko commented on src/hooks/useDebouncedValue.ts
>  export const useDebouncedValue = <T extends Primitives>(value: T, delay: number): T => {
Я исправил на строку, но интересно, почему здесь только строка подходит? Потому что на практике только строку надо так обрабатывать или почему?

2024-01-25 09:35 UTC, MariyaKustova commented on src/hooks/useDebouncedValue.ts
>  export const useDebouncedValue = <T extends Primitives>(value: T, delay: number): T => {
Пользователь может ввести в инпут только строку

2024-01-25 09:42 UTC, Kirillishko commented on src/hooks/useDebouncedValue.ts
>  export const useDebouncedValue = <T extends Primitives>(value: T, delay: number): T => {
Хорошо, понял.

2024-01-25 09:52 UTC, st-slav commented on src/pages/ProductPage/ProductPage.tsx
> +    //
комментарии

2024-01-25 09:52 UTC, st-slav commented on src/pages/ProductListPage/ProductListPage.tsx
> +    // return filteredProducts && filteredProducts.length > 0 ? (
комментарии

2024-01-25 09:54 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +    // return filteredProducts && filteredProducts.length > 0 ? (
Убрал.

2024-01-25 09:54 UTC, Kirillishko commented on src/pages/ProductPage/ProductPage.tsx
> +    //
Убрал.

2024-01-25 10:02 UTC, MariyaKustova commented on src/pages/ProductPage/ProductPage.tsx
> +    }
Описала действия выше

2024-01-25 10:02 UTC, MariyaKustova commented on src/pages/ProductPage/ProductPage.tsx
> +
Убрать

2024-01-25 10:02 UTC, MariyaKustova commented on src/pages/ProductPage/ProductPage.tsx
> +                <div >К сожалению, список пуст!</div >
Это страница товара. Здесь может быть ситуация только одна - товар не найден

2024-01-25 10:18 UTC, st-slav commented on src/hooks/useData.ts
> +    useEffect(() => {
```
const useData = (fetch?: () => Promise | null): {
    isLoading: boolean,
    error: string | null,
    data: IProduct | IProduct[] | null;
} => {
    const [data, setData] = useState<IProduct | IProduct[] | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (fetch) {
            setIsLoading(true);
            const fetch = id ? () => getItem(id) : getItems;
            fetch()
                .then(data => {
                    setData(data);
                })
                .catch(error => {
                    setError(error.message);
                }).finally(() => {
                setIsLoading(false);
            });
        }
    }, [fetch]);

    return {isLoading, error, data};
};
```

и использовать:
```
const getById = useCallback(() => {
return getIten(id)
}, [id])
const query = useData(id ? getById : null)
```

2024-01-25 10:43 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +    // );
Сделал.

2024-01-25 11:34 UTC, Kirillishko commented on src/pages/ProductListPage/ProductListPage.tsx
> +
Исправил, добавил сверху справа кнопку, чтобы вернуться на главную страницу.

2024-01-25 11:34 UTC, Kirillishko commented on src/pages/ProductPage/ProductPage.tsx
> +    }
Сделал.

2024-01-25 11:34 UTC, Kirillishko commented on src/pages/ProductPage/ProductPage.tsx
> +
Убрал.

2024-01-25 11:34 UTC, Kirillishko commented on src/pages/ProductPage/ProductPage.tsx
> +                <div >К сожалению, список пуст!</div >
Исправил.

2024-01-25 11:34 UTC, Kirillishko commented on src/hooks/useData.ts
> +    useEffect(() => {
Исправил, спасибо.

2024-01-25 11:36 UTC, st-slav approved these changes

2024-01-25 11:36 UTC, merged